name: Test

on:
  push:
    branches:
      - main
      - feature/**
    tags:
      - "*"
  pull_request:
    paths:
      - "src/**"
      - ".github/**"

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - name: Rustup
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
